# Generated by Django 4.2.1 on 2023-06-06 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_pj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acto', models.CharField(max_length=200)),
                ('solicitudes_de_investigacion', models.CharField(max_length=50)),
                ('organos_creados', models.CharField(max_length=500)),
                ('regula_los_organos', models.CharField(max_length=500)),
                ('designa_A', models.CharField(max_length=500)),
                ('gaceta_de_origen', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fecha_de_publicacion', models.DateField()),
                ('organo_emisor', models.CharField(max_length=200)),
                ('contenido_acto', models.TextField()),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gacetas_oficiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('actos', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('tipo_de_gaceta', models.CharField()),
                ('territorialidad', models.CharField()),
                ('sumario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='organismos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organos', models.CharField(max_length=200)),
                ('solicitudes_de_investigacion', models.CharField(max_length=50)),
                ('ministerio_principal', models.CharField(max_length=50)),
                ('subordinado_A', models.CharField(max_length=50)),
                ('cordinado_Por', models.CharField(max_length=50)),
                ('acto_de_creacion', models.CharField(max_length=200)),
                ('nr_de_gaceta_creacion', models.IntegerField()),
                ('acto_que_regula_su_organismo', models.TextField()),
                ('nr_de_gaceta_acto_organizacion', models.IntegerField()),
                ('encargado_actual', models.CharField(max_length=200)),
                ('acto_de_designacion', models.CharField()),
                ('nr_de_gaceta_acto_designacion', models.IntegerField()),
                ('notas', models.TextField()),
                ('actos_emitidos', models.TextField()),
                ('funcion_publica', models.CharField(max_length=50)),
                ('territorialidad', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('ubicacion_oficinas', models.TextField()),
                ('fecha_designacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PEPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('organismos', models.CharField(max_length=200)),
                ('acto_de_designacion', models.CharField()),
                ('fecha_designacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitudes_de_investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('solicitante', models.TextField(max_length=50)),
                ('organismos_relacionados', models.CharField(max_length=200)),
                ('actos_relacionados', models.CharField(max_length=200)),
                ('adjunto', models.FileField(upload_to='')),
                ('fecha_de_solicitud', models.DateField()),
                ('respuesta', models.TextField()),
                ('respuesta_aprobada', models.BooleanField()),
                ('fecha_de_respuesta', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo_electronico_afiliado',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_de_cancelacion',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nr_documento_identidad',
            field=models.IntegerField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='solicitudes_de_investigacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_de_documento_identificatorio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='solicitudes_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitudes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.solicitudes_de_investigacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudes_organismos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_organismos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.organismos')),
                ('id_solicitudes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.solicitudes_de_investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudes_actos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.actos')),
                ('id_solicitudes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.solicitudes_de_investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='organismos_peps_actas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.actos')),
                ('id_organismos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.organismos')),
                ('id_peps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.peps')),
            ],
        ),
        migrations.CreateModel(
            name='organismos_peps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_organismos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.organismos')),
                ('id_peps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.peps')),
            ],
        ),
        migrations.CreateModel(
            name='organismos_actos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.actos')),
                ('id_organismos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.organismos')),
            ],
        ),
        migrations.CreateModel(
            name='gacetas_actos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.actos')),
                ('id_gacetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_pj.gacetas_oficiales')),
            ],
        ),
    ]
