# Generated by Django 4.2.1 on 2023-06-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_pj', '0002_actos_gacetas_oficiales_organismos_peps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nr_documento_identidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
