# Generated by Django 4.2.1 on 2023-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_pj', '0003_alter_usuarios_nr_documento_identidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actos',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actos',
            name='contenido_acto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actos',
            name='designa_A',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actos',
            name='organo_emisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actos',
            name='organos_creados',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actos',
            name='regula_los_organos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actos',
            name='solicitudes_de_investigacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='acto_de_creacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='acto_que_regula_su_organismo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='actos_emitidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='cordinado_Por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='ministerio_principal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='nr_de_gaceta_acto_organizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='nr_de_gaceta_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='solicitudes_de_investigacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='subordinado_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='ubicacion_oficinas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes_de_investigacion',
            name='actos_relacionados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes_de_investigacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitudes_de_investigacion',
            name='fecha_de_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes_de_investigacion',
            name='organismos_relacionados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes_de_investigacion',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes_de_investigacion',
            name='respuesta_aprobada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='solicitudes_de_investigacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
