# Generated by Django 4.1.7 on 2023-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_pj', '0004_alter_actos_contenido_alter_actos_contenido_acto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gacetas_oficiales',
            name='territorialidad',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gacetas_oficiales',
            name='tipo_de_gaceta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='acto_de_designacion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='peps',
            name='acto_de_designacion',
            field=models.CharField(max_length=500),
        ),
    ]
