# Generated by Django 4.1.7 on 2023-06-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_pj', '0005_alter_gacetas_oficiales_territorialidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actos',
            options={'verbose_name_plural': 'Actos'},
        ),
        migrations.AlterModelOptions(
            name='gacetas_oficiales',
            options={'verbose_name_plural': 'Gacetas Oficiales'},
        ),
        migrations.AlterModelOptions(
            name='organismos',
            options={'verbose_name_plural': 'Organismos'},
        ),
        migrations.AlterModelOptions(
            name='peps',
            options={'verbose_name_plural': 'PEPs'},
        ),
        migrations.AlterModelOptions(
            name='solicitudes_de_investigacion',
            options={'verbose_name_plural': 'Solicitudes de investigacion'},
        ),
        migrations.AlterModelOptions(
            name='solicitudes_usuarios',
            options={'verbose_name_plural': 'Solicitudes/Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'usuarios'},
        ),
    ]
